version: 0.2

phases:
  install:
    commands:
      - cd client # Change to the client directory
      - npm install # Install dependencies in the client folder
  build:
    commands:
      - npm run build # Build the project inside the client directory
artifacts:
  files:
    - "**/*"
  base-directory: client/build # Directory with the output files (e.g., React app)
